In [8]:
%load_ext autoreload
%autoreload 2

from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd().parents[1]   # adjust if needed
DATA_DIR = PROJECT_ROOT / "data"

massey = pd.read_csv(DATA_DIR / "MMasseyOrdinals.csv")

massey.head()

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

   Season  RankingDayNum SystemName  TeamID  OrdinalRank
0    2003             35        SEL    1102          159
1    2003             35        SEL    1103          229
2    2003             35        SEL    1104           12
3    2003             35        SEL    1105          314
4    2003             35        SEL    1106          260

In [9]:
print(massey.shape)
print(massey.columns.tolist())
massey.head()

(5865001, 5)
['Season', 'RankingDayNum', 'SystemName', 'TeamID', 'OrdinalRank']

   Season  RankingDayNum SystemName  TeamID  OrdinalRank
0    2003             35        SEL    1102          159
1    2003             35        SEL    1103          229
2    2003             35        SEL    1104           12
3    2003             35        SEL    1105          314
4    2003             35        SEL    1106          260

In [10]:
massey_consensus = (
    massey
    .groupby(["Season", "RankingDayNum", "TeamID"])["OrdinalRank"]
    .median()
    .reset_index(name="consensus_rank")
)

print(massey_consensus.shape)
massey_consensus.head()

(270746, 4)

   Season  RankingDayNum  TeamID  consensus_rank
0    2003             35    1102           159.0
1    2003             35    1103           229.0
2    2003             35    1104            12.0
3    2003             35    1105           314.0
4    2003             35    1106           260.0

In [11]:
print(massey_consensus["RankingDayNum"].min())
print(massey_consensus["RankingDayNum"].max())

print(
    massey_consensus
    .groupby("Season")["RankingDayNum"]
    .nunique()
    .describe()
)

0
133
count    24.000000
mean     35.625000
std      20.357271
min      16.000000
25%      18.000000
50%      19.500000
75%      54.000000
max      69.000000
Name: RankingDayNum, dtype: float64

In [12]:
games_team1 = raw_X[
    ["Season", "DayNum", "team_1_id"]
].copy()

games_team1 = games_team1.sort_values(
    ["Season", "DayNum", "team_1_id"]
)

massey_team1 = massey_consensus.rename(
    columns={
        "TeamID": "team_1_id",
        "consensus_rank": "team_1_massey_rank"
    }
).sort_values(
    ["Season", "RankingDayNum", "team_1_id"]
)

team1_with_rank = pd.merge_asof(
    games_team1,
    massey_team1,
    left_on="DayNum",
    right_on="RankingDayNum",
    by=["Season", "team_1_id"],
    direction="backward"
)

team1_with_rank.head(20)

NameError: name 'raw_X' is not defined